### ISSUE TITLE
Not Returing any results for Walmart

### ISSUE THREAD

**Issue by raj1985msit2** [ericpp/nesstocks#1]
Hello,
The code is not returning any output for Walmart. The output is being terminated with an exception.
Fatal error: Maximum execution time of 30 seconds exceeded in \src\HttpClient.php on line 55

Can you please help me out and fix this?

Thanks,

**Comment by ericpp** [comment]
It sounds like it can't connect to the Walmart website. Are you able to load this URL: https://www.walmart.com/terra-firma/item/5VRQ98YB00LF/location/55455?selected=true&wl13= ?

**Comment by raj1985msit2** [comment]
The link is returning the code as shown below

{"status":"OK","errors":[{"code":"IRO BY_PRODUCT_ID [PRODUCT_ASSET, OFFER_PRODUCT, OFFER_PRICE, OFFER_INVENTORY, ESTIMATED_SHIP_PRICE, VARIANT_SUMMARY, PROMISE_DATE][5VRQ98YB00LF]

What do we do for this?

Thanks,

**Comment by ericpp** [comment]
That is the URL that the script uses to check stock. I just wanted to see if it was working for you outside of the script.

Are you running the script on your computer or on a server? If on a server, do you know if it allows outbound connections? Do you know which version of PHP you're using? I've only tested it with Ubuntu PHP 5.5.9.

**Comment by raj1985msit2** [comment]
I am running it on xampp. The scripts runs fine for Target and creates the output file with item availability but for some reason it gets terminated after 30 seconds. For Walmart it is not returning any results. 
So I am not sure, how to figure it out.
Is everything running fine for you?

If yes, do you have a standalone installation for this or are you running it on your laptop like I am doing it?

Thank you

**Comment by ericpp** [comment]
It seems like it was failing on validating the SSL certificate for Walmart. Should be fixed now.

**Comment by ericpp** [comment]
I've tried it on XAMPP 5.5.38, 5.6.28, and 7.0.13 and all work on my computer. I'm not sure why it's timing out on your computer.

**Comment by raj1985msit2** [comment]
I had to increase the time out settings on my Xampp, so I am not getting the time out any more.

Thank you very much for your help.

I really appreaciate it.
